# render.yaml
services:
  - type: web
    name: yuddhishthir-backend
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      pip install pandas
    startCommand: uvicorn backend:app --host 0.0.0.0 --port 8000